version: '3'
services:
  golf-club-api:
    image: golf-club-api:latest
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_USER=root
      - DB_PASSWORD=Skittles98
      - DB_NAME=golf_club_api
